---
# httplib2 is required in order to use ansible's uri module
- name: install httplib2
  sudo: true
  apt: pkg="{{python_pkg_prefix}}-httplib2"

- name: install some common ground
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - acl
    - build-essential
    - git-core
    - unzip

- name: configure SSHD (port)
  lineinfile: dest=/etc/ssh/sshd_config
              regexp='^Port (\d+)'
              line="Port {{ssh_port}}"
              backrefs=yes
  notify: restart ssh
